"""Reject distributions that lose or change reproducibility inputs."""

import io
import tarfile
import venv
from pathlib import Path
from zipfile import ZipFile

import pytest

from scripts import check_distribution
from scripts.check_distribution import check_contents


@pytest.fixture
def source_files(tmp_path: Path) -> dict[str, bytes]:
    """Create a small checkout with files beyond the original smoke-test examples."""
    files = {
        "LICENSE": b"license\n",
        "README.md": b"readme\n",
        "pyproject.toml": b"[project]\n",
        "poetry.lock": b"# lock\n",
        "articles/manifest.yml": b"articles: {}\n",
        "articles/manifest.schema.json": b"{}\n",
        "src/blog_reproducibility/__init__.py": b"",
        "src/blog_reproducibility/physics/seasons.py": b"VALUE = 1\n",
        "src/blog_reproducibility/common/house.mplstyle": b"figure.dpi: 100\n",
        "src/blog_reproducibility/py.typed": b"",
        "scripts/figures/physics/seasons.py": b"print('seasons')\n",
        "scripts/benchmarks/example.py": b"print('benchmark')\n",
        "tests/physics/test_seasons.py": b"def test_value(): pass\n",
        "data/economics/vintages.csv": b"date,value\n2025-01-01,42\n",
        "data/SHA256SUMS": b"checksum inventory\n",
    }
    for name, content in files.items():
        path = tmp_path / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
    return files


def write_distributions(
    directory: Path, source_files: dict[str, bytes], wheel_files: dict[str, bytes]
) -> tuple[Path, Path]:
    """Build tiny real archives without installing a package or accessing the network."""
    wheel = directory / "example.whl"
    with ZipFile(wheel, "w") as wheel_archive:
        for name, content in wheel_files.items():
            wheel_archive.writestr(name, content)
        wheel_archive.writestr("example-0.1.0.dist-info/METADATA", "Name: example\n")
    source = directory / "example.tar.gz"
    with tarfile.open(source, "w:gz") as source_archive:
        for name, content in source_files.items():
            member = tarfile.TarInfo("example-0.1.0/" + name)
            member.size = len(content)
            source_archive.addfile(member, io.BytesIO(content))
        metadata = tarfile.TarInfo("example-0.1.0/PKG-INFO")
        source_archive.addfile(metadata, io.BytesIO())
    return wheel, source


@pytest.fixture
def wheel_files(source_files: dict[str, bytes]) -> dict[str, bytes]:
    return {
        name.removeprefix("src/"): content
        for name, content in source_files.items()
        if name.startswith("src/")
    }


def test_complete_distributions_match_checkout(
    tmp_path: Path, source_files: dict[str, bytes], wheel_files: dict[str, bytes]
) -> None:
    # Local bytecode is generated by validation, not a required source input.
    cache = tmp_path / "src/blog_reproducibility/__pycache__/__init__.cpython-313.pyc"
    cache.parent.mkdir()
    cache.write_bytes(b"cache")
    (tmp_path / "scripts/cached.pyo").write_bytes(b"cache")
    wheel, source = write_distributions(tmp_path, source_files, wheel_files)
    check_contents(wheel, source, root=tmp_path)


@pytest.mark.parametrize("change", ["missing", "changed"])
@pytest.mark.parametrize(
    "path",
    [
        "blog_reproducibility/physics/seasons.py",
        "blog_reproducibility/common/house.mplstyle",
        "blog_reproducibility/py.typed",
    ],
)
def test_wheel_must_preserve_modules_and_resources(
    tmp_path: Path,
    source_files: dict[str, bytes],
    wheel_files: dict[str, bytes],
    path: str,
    change: str,
) -> None:
    if change == "missing":
        del wheel_files[path]
    else:
        wheel_files[path] += b"altered"
    wheel, source = write_distributions(tmp_path, source_files, wheel_files)
    with pytest.raises(RuntimeError) as error:
        check_contents(wheel, source, root=tmp_path)
    assert "Wheel differs from the checkout" in str(error.value)
    assert f"{change}=['{path}']" in str(error.value)


@pytest.mark.parametrize("change", ["missing", "changed"])
@pytest.mark.parametrize(
    "path",
    [
        "src/blog_reproducibility/physics/seasons.py",
        "scripts/figures/physics/seasons.py",
        "scripts/benchmarks/example.py",
        "tests/physics/test_seasons.py",
        "data/economics/vintages.csv",
        "data/SHA256SUMS",
        "articles/manifest.yml",
        "articles/manifest.schema.json",
        "poetry.lock",
    ],
)
def test_source_archive_must_preserve_reproduction_inputs(
    tmp_path: Path,
    source_files: dict[str, bytes],
    wheel_files: dict[str, bytes],
    path: str,
    change: str,
) -> None:
    if change == "missing":
        del source_files[path]
    else:
        source_files[path] += b"altered"
    wheel, source = write_distributions(tmp_path, source_files, wheel_files)
    with pytest.raises(RuntimeError) as error:
        check_contents(wheel, source, root=tmp_path)
    assert "Source archive differs from the checkout" in str(error.value)
    assert f"{change}=['{path}']" in str(error.value)


@pytest.mark.parametrize("artifact", ["wheel", "source"])
def test_command_rejects_incomplete_distributions_before_installing(
    tmp_path: Path,
    source_files: dict[str, bytes],
    wheel_files: dict[str, bytes],
    monkeypatch: pytest.MonkeyPatch,
    artifact: str,
) -> None:
    def unexpected_environment(*args: object, **kwargs: object) -> None:
        pytest.fail("Incomplete distributions must fail before creating an environment")

    monkeypatch.setattr(check_distribution, "ROOT", tmp_path)
    monkeypatch.setattr(venv, "EnvBuilder", unexpected_environment)
    if artifact == "wheel":
        del wheel_files["blog_reproducibility/physics/seasons.py"]
    else:
        del source_files["data/economics/vintages.csv"]
    destination = tmp_path / "dist"
    destination.mkdir()
    write_distributions(destination, source_files, wheel_files)
    with pytest.raises(RuntimeError, match="differs from the checkout"):
        check_distribution.main()
