"""Generate the article reference from the validated reproducibility manifest."""

import argparse
import sys
from pathlib import Path

import yaml

from scripts.manifest import ROOT, Article, load_manifest


def render_catalog(articles: dict[str, Article]) -> str:
    """Link every registered article to its implementation, tests, and outputs."""
    figures = sum(len(article.figures) for article in articles.values())
    drafts = sum(article.publication_status == "draft" for article in articles.values())
    lines = [
        "# Article catalog",
        "",
        "<!-- Generated by python -m scripts.catalog; edit articles/manifest.yml instead. -->",
        "",
        f"{len(articles) - drafts} published articles · {drafts} drafts · {figures} figures",
        "",
        "Regenerate all figures with `poetry run python -m scripts.reproduce`.",
        "Use `--article IDENTIFIER` for one article, `--domain DOMAIN` for a subject,",
        "or `--list --search TEXT` to find a computation. Add `--json` to export a listing.",
        "",
        "| Domain | Articles | Figures |",
        "| --- | ---: | ---: |",
    ]
    domains = sorted({domain for article in articles.values() for domain in article.domains})
    for domain in domains:
        group = [article for article in articles.values() if domain in article.domains]
        lines.append(f"| {domain} | {len(group)} | {sum(len(a.figures) for a in group)} |")
    for identifier, article in sorted(articles.items()):
        lines.extend(
            [
                "",
                f"## {identifier}",
                "",
                f"[Article source]({article.source_url})"
                f" · {article.publication_status.capitalize()}"
                f" · Domain: {', '.join(article.domains)}",
                "",
                "```console",
                f"poetry run python -m scripts.reproduce --article {identifier}",
                "```",
                "",
                "| Resource | Location |",
                "| --- | --- |",
            ]
        )
        for module in article.modules:
            path = Path("src", *module.split(".")).with_suffix(".py")
            lines.append(f"| Module | [{module}](../{path.as_posix()}) |")
        if article.benchmark_harness is not None:
            harness_path = article.benchmark_harness.as_posix()
            lines.append(f"| Manual benchmark | [{harness_path}](../{harness_path}) |")
        for category, paths in (
            ("Script", article.scripts),
            ("Test", article.tests),
            ("Input", article.inputs),
        ):
            for path in paths:
                lines.append(f"| {category} | [{path.as_posix()}](../{path.as_posix()}) |")
        for figure in article.figures:
            lines.append(f"| Generated figure | `{figure.as_posix()}` |")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    """Write the catalog or fail when the checked-in version is stale."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check without writing files.")
    args = parser.parse_args(argv)
    path = ROOT / "docs/articles.md"
    try:
        content = render_catalog(load_manifest())
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                print(
                    "Article catalog is stale; run poetry run python -m scripts.catalog.",
                    file=sys.stderr,
                )
                return 1
            print("Article catalog is up to date.")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
            print(f"Updated {path}")
    except (OSError, ValueError, yaml.YAMLError) as error:
        print(f"Catalog failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
